import Providers from "@/providers/walletconnect";
import type { Metadata } from "next";
import "./globals.css";
import Layout from "./layout/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers />
      <Layout children={children}/>
    </html>
  );
}
